<a href="https://colab.research.google.com/github/dilaraesmer/FreeCodeCamp/blob/main/NumPy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import sys
import numpy as np

In [3]:
n = 3

In [4]:
2 ** 3

8

In [5]:
x = 5

In [6]:
np.int8

numpy.int8

In [7]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [8]:
a = np.array([1,2,3,4])

In [9]:
b = np.array([0, .5, 1, 1.5, 2])

In [11]:
a[0], a[1]

(1, 2)

In [12]:
a[:2]

array([1, 2])

In [13]:
a[0:]

array([1, 2, 3, 4])

In [14]:
a[1:3]

array([2, 3])

In [15]:
a[1:-1]

array([2, 3])

In [16]:
a[::2]

array([1, 3])

In [17]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [18]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [19]:
b[[0,2,-1]]

array([0., 1., 2.])

Array Types

In [20]:
a

array([1, 2, 3, 4])

In [21]:
a.dtype

dtype('int64')

In [22]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [23]:
b.dtype

dtype('float64')

In [24]:
np.array([1,2,3,4], dtype = np.float)

<ipython-input-24-2949a392c07b>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1,2,3,4], dtype = np.float)


array([1., 2., 3., 4.])

In [26]:
np.array([1,2,3,4], dtype = np.int8)

array([1, 2, 3, 4], dtype=int8)

In [25]:
c = np.array(['a', 'b', 'c'])

In [27]:
c.dtype

dtype('<U1')

In [28]:
d = np.array([{'a': 1}, sys])

In [29]:
d.dtype

dtype('O')

Dimensions and shapes

In [30]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [31]:
A.shape

(2, 3)

In [32]:
A.ndim

2

In [33]:
A.size

6

In [38]:
B = np.array([
    [
    [12,12,10],
    [9,8,7],
], 
[
    [6,5,4],
    [3,2,1]
    ]
])

In [39]:
B.shape

(2, 2, 3)

In [40]:
B.ndim

3

In [41]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [42]:
C = np.array([
    [
    [12,12,10],
    [9,8,7],
], 
[
    [6,5,4],
    ]
])

<ipython-input-42-64986918157c>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [43]:
C.dtype

dtype('O')

In [44]:
C.shape

(2,)

In [45]:
C.size

2

In [46]:
type(C[0])

list

Indexing and Slicing of Matrices

In [47]:
# Square matrix
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [48]:
A[1]

array([4, 5, 6])

In [49]:
A[1][0]

4

In [50]:
A[1,0]

4

In [51]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
A[:, :3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
A[:2, 2:]

array([[3],
       [6]])

In [55]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
A[1] = np.array([10,10,10])

In [57]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [58]:
A[2] = 99

In [59]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])