<a href="https://colab.research.google.com/github/dilaraesmer/FreeCodeCamp/blob/main/NumPy_intro_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Broadcasting and Vectorized operations

In [4]:
import numpy as np

In [19]:
a = np.arange(4)

In [20]:
a

array([0, 1, 2, 3])

In [21]:
a + 14

array([14, 15, 16, 17])

In [22]:
a+=14

In [24]:
a

array([14, 15, 16, 17])

In [25]:
l = [0,1,2,3]

In [26]:
[i * 10 for i in l ]

[0, 10, 20, 30]

In [27]:
a = np.arange(4)

In [28]:
a

array([0, 1, 2, 3])

In [29]:
b = np.array([10,10,10,10])

In [30]:
b

array([10, 10, 10, 10])

In [31]:
a + b

array([10, 11, 12, 13])

In [32]:
a * b

array([ 0, 10, 20, 30])