<a href="https://colab.research.google.com/github/dilaraesmer/FreeCodeCamp/blob/main/NumPy_intro_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Broadcasting and Vectorized operations

In [61]:
import numpy as np
import sys

In [19]:
a = np.arange(4)

In [20]:
a

array([0, 1, 2, 3])

In [21]:
a + 14

array([14, 15, 16, 17])

In [22]:
a+=14

In [24]:
a

array([14, 15, 16, 17])

In [25]:
l = [0,1,2,3]

In [26]:
[i * 10 for i in l ]

[0, 10, 20, 30]

In [27]:
a = np.arange(4)

In [28]:
a

array([0, 1, 2, 3])

In [29]:
b = np.array([10,10,10,10])

In [30]:
b

array([10, 10, 10, 10])

In [31]:
a + b

array([10, 11, 12, 13])

In [32]:
a * b

array([ 0, 10, 20, 30])

Boolean Arrays

In [33]:
a = np.arange(4)

In [34]:
a[[0,-1]]

array([0, 3])

In [35]:
a[[True, False, False, True]]

array([0, 3])

In [37]:
a >= 2

array([False, False,  True,  True])

In [38]:
a[a >= 2]

array([2, 3])

In [39]:
a.mean()

1.5

In [40]:
a[a > a.mean()]

array([2, 3])

In [41]:
a[~(a > a.mean())]

array([0, 1])

In [42]:
a[(a == 0) | a == 1]

array([0, 1])

In [43]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [44]:
A = np.random.randint(100, size=(3,3))

In [45]:
A

array([[32, 77, 37],
       [36, 89, 18],
       [51, 87,  9]])

In [50]:
A[np.array([
    [True, False, True],
    [True, True, False], 
    [True, False, True]
])]

array([32, 37, 36, 89, 51,  9])

In [51]:
A > 30

array([[ True,  True,  True],
       [ True,  True, False],
       [ True,  True, False]])

In [52]:
A[A>30]

array([32, 77, 37, 36, 89, 51, 87])

Linear Algebra

In [53]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [54]:
B = np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [55]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [56]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [57]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [58]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

Size of Objects in Memory

Int, floats

In [62]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [63]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [64]:
# Numpy is much smaller
np.dtype(int).itemsize

8

In [65]:
np.dtype(float).itemsize

8

Lists are even larger

In [66]:
# A one-element list
sys.getsizeof([1])

64

In [67]:
# an Array of one element in numpy
np.array([1]).nbytes

8

And performance is also important 

In [68]:
l = list(range(1000))

In [69]:
a = np.arange(1000)

In [70]:
%time np.sum(a ** 2)

CPU times: user 0 ns, sys: 315 µs, total: 315 µs
Wall time: 313 µs


332833500

In [71]:
%time np.sum([x ** 2 for x in l])

CPU times: user 1.97 ms, sys: 0 ns, total: 1.97 ms
Wall time: 1.99 ms


332833500

Useful Numpy functions

random

In [72]:
np.random.random(size=2)

array([0.15023643, 0.4992618 ])

In [73]:
np.random.normal(size=2)

array([-3.05219594, -1.47687883])

In [75]:
np.random.rand(2,4)

array([[0.00452781, 0.75787443, 0.67044817, 0.16082543],
       [0.66918975, 0.26425523, 0.335867  , 0.64818067]])

arange

In [74]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [77]:
np.arange(0,1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

reshape

In [78]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [79]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

linspace

In [80]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [81]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [82]:
np.linspace(0,1,20,False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

zeros, ones, empty

In [83]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [84]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [85]:
np.zeros((3,3), dtype=(int))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [86]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [87]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [89]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [90]:
np.empty((2,2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])