<a href="https://colab.research.google.com/github/dilaraesmer/FreeCodeCamp/blob/main/NumPy_intro_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Broadcasting and Vectorized operations

In [4]:
import numpy as np

In [19]:
a = np.arange(4)

In [20]:
a

array([0, 1, 2, 3])

In [21]:
a + 14

array([14, 15, 16, 17])

In [22]:
a+=14

In [23]:
a

array([14, 15, 16, 17])